branches:
  # release branch
  - main

  # maintenance branch
  - name: '+([0-9])?(.{+([0-9]),x}).x'

  # prerelease branch
  - name: next
    prerelease: rc
    channel: '${name}'

tagFormat: v${version}

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
      changelogTitle: '# PWS Library Manager v1 Changelog'
  - - '@semantic-release/exec'
    - analyzeCommitsCmd: |
        echo "${lastRelease.version}" > .lastRelease.txt
      verifyReleaseCmd: |
        echo "${nextRelease.version}" > .nextRelease.txt
      publishCmd: |
        export NEXT_RELEASE_VERSION=$(cat .nextRelease.txt)
        if [[ $NEXT_RELEASE_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Publishing $NEXT_RELEASE_VERSION as release"
          echo $NEXT_RELEASE_VERSION > app.version
        elif [[ $NEXT_RELEASE_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+-.+$ ]]; then
          echo "Publishing $NEXT_RELEASE_VERSION as snapshot"
          echo "${NEXT_RELEASE_VERSION%-*}-SNAPSHOT" > app.version
          sbt publish
        else
          echo "No release published"
        fi