branches:
  # release branch
  - main

  # maintenance branch
  - name: '+([0-9])?(.{+([0-9]),x}).x'

  # prerelease branch
  - name: next
    prerelease: rc
    channel: '${name}'

  - name: feature/pws-lib-converter
    prerelease: alpha
    channel: '${name}'

tagFormat: v${version}

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
      changelogTitle: '# PWS Library Manager v1 Changelog'
  - - '@semantic-release/exec'
    - analyzeCommitsCmd: |
        echo "${lastRelease.version}" > .lastRelease.txt
      verifyReleaseCmd: |
        echo "${nextRelease.version}" > .nextRelease.txt
      publishCmd: ./publish.sh