name: CI

on:
  push:
  pull_request:
    branches: [ "main", "next" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run tests
        run: sbt test
      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
      - name: Install semantic-release
        run: npm install --global semantic-release@22.0.12 @semantic-release/changelog@6.0.3 @semantic-release/git@10.0.1 @semantic-release/github@9.2.5 @semantic-release/exec@6.0.3
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: APP Version
          path: app.version
          retention-days: 30
