name: CI

on:
  push:
  pull_request:
    branches: [ "main", "next" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run tests
        run: sbt test
      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
